# Generated by Django 5.0.4 on 2024-05-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
