# Generated by Django 5.0.4 on 2024-05-10 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffportal', '0002_customuser_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapproval',
            name='loan_application',
        ),
        migrations.AddField(
            model_name='loanapproval',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
