# Generated by Django 5.0.4 on 2024-05-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffportal', '0004_customuser_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accname', models.CharField(blank=True, max_length=100, null=True)),
                ('accdesc', models.CharField(blank=True, max_length=2500, null=True)),
                ('acciamge', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
    ]
