# Generated by Django 5.0.4 on 2024-05-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=600, null=True)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('aadhar', models.CharField(max_length=200, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
