# Generated by Django 5.0.4 on 2024-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='aadhar_number',
            field=models.CharField(default=0, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='savings',
            name='phone_number',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
    ]
