# Generated by Django 5.0.4 on 2024-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0002_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
