# Generated by Django 5.0.4 on 2024-05-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0005_alter_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='budget',
        ),
    ]
