# Generated by Django 5.0.4 on 2024-05-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0005_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
