# Generated by Django 5.0.4 on 2024-05-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0006_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
