# Generated by Django 5.0.4 on 2024-05-08 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='balance',
            new_name='initial_deposit',
        ),
        migrations.AddField(
            model_name='savings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
