# Generated by Django 5.0.4 on 2024-05-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0009_rename_balance_savings_initial_deposit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='initial_deposit',
            new_name='balance',
        ),
    ]
